declare const __dirname: string;
declare const process: {
  argv: string[];
  exit: (code?: number) => never;
};
declare const require: (name: string) => any;

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..', '..');
const files = [
  'build/esm/puddi/puddi.js',
  'build/esm/puddi/puddiobject.js',
  'build/esm/circle.js',
  'build/esm/square.js',
  'build/esm/triangle.js',
  'build/esm/edu/label.js',
  'build/esm/edu/tooltip.js',
  'build/esm/edu/grid.js',
  'build/esm/edu/axis2d.js',
  'build/esm/edu/vector-arrow.js',
  'build/esm/edu/draggable.js',
  'build/esm/edu/selectable.js',
  'build/esm/demos/orbiting.js',
  'build/esm/demos/mouse-drawing.js',
  'build/esm/demos/follow-chain.js',
  'build/esm/demos/pendulum-trail.js',
  'build/esm/demos/procedural-grid.js',
  'build/esm/demos/particle-burst.js',
  'build/esm/demos/lissajous.js',
  'build/esm/demos/boids-lite.js',
  'build/esm/demos/spring-chain.js',
  'build/esm/demos/waves-refraction.js',
  'build/esm/demos/cursor-magnet.js',
  'build/esm/demos/gravity-sandbox.js',
  'build/esm/demos/orrery.js',
  'build/esm/demos/mandala-bloom.js',
  'build/esm/demos/articulated-creature.js',
  'build/esm/demos/vector-decomposition.js',
  'build/esm/demos/dot-product-projection.js',
  'build/esm/demos/linear-transform-playground.js',
  'build/esm/demos/function-plotter.js',
  'build/esm/demos/bezier-casteljau.js',
  'build/esm/demos/pathfinding-grid.js',
  'build/esm/demos/sorting-visualizer.js',
  'build/esm/demos/interaction-torture-lab.js',
  'build/esm/demos/index.js',
  'build/esm/main.js',
];

function stripModuleSyntax(content: string): string {
  return content
    .replace(/^\s*import .*$/gm, '')
    .replace(/^export function /gm, 'function ')
    .replace(/^export class /gm, 'class ')
    .replace(/^export (const|let|var) /gm, '$1 ')
    .replace(/^export default class /gm, 'class ')
    .replace(/^export default function /gm, 'function ')
    .replace(/^export default .*;\s*$/gm, '')
    .replace(/^export \{[^}]*\};?\s*$/gm, '')
    .trim();
}

const parts = files.map((file) => {
  const fullPath = path.join(root, file);
  const content = fs.readFileSync(fullPath, 'utf8');
  return stripModuleSyntax(content);
});

const banner = "/* Generated by build/esm/build.js. */\n(function () {\n'use strict';\n";
const footer = '\n})();\n';
const output = banner + parts.join('\n\n') + footer;

async function build(): Promise<void> {
  const args = new Set(process.argv.slice(2));
  const shouldMinify = args.has('--minify') || args.has('-m');

  let finalOutput = output;

  if (shouldMinify) {
    let terser: any;
    try {
      terser = require('terser');
    } catch (err) {
      console.error('Missing dependency: terser. Run `npm install` to enable minify.');
      process.exit(1);
    }

    const result = await terser.minify(finalOutput);
    if (result.error) {
      console.error('Terser minify failed:', result.error);
      process.exit(1);
    }

    finalOutput = result.code;
  }

  const distDir = path.join(root, 'dist');
  fs.mkdirSync(distDir, { recursive: true });

  const outPath = path.join(distDir, 'bundle.js');
  fs.writeFileSync(outPath, finalOutput, 'utf8');
  console.log('Wrote dist/bundle.js');

  const vendorDir = path.join(distDir, 'vendor');
  fs.mkdirSync(vendorDir, { recursive: true });

  const threeEntry = path.join(root, 'node_modules', 'three', 'build', 'three.module.js');
  if (!fs.existsSync(threeEntry)) {
    console.error('Missing dependency: three. Run `npm install`.');
    process.exit(1);
  }

  let esbuild: any;
  try {
    esbuild = require('esbuild');
  } catch (err) {
    console.error('Missing dependency: esbuild. Run `npm install`.');
    process.exit(1);
  }

  await esbuild.build({
    entryPoints: [threeEntry],
    bundle: true,
    format: 'iife',
    globalName: 'THREE',
    minify: true,
    platform: 'browser',
    outfile: path.join(vendorDir, 'three.min.js'),
  });
  console.log('Wrote dist/vendor/three.min.js');
}

build().catch((err: unknown) => {
  console.error('Build failed:', err);
  process.exit(1);
});
